In [1]:
import numpy as np
import scipy as sp

In [2]:
A = np.array([
    [2,  1, -1,  3],
    [4, -2,  5,  1],
    [-1, 3,  2, -4],
    [3, -1,  4,  2]
])

print(A)

[[ 2  1 -1  3]
 [ 4 -2  5  1]
 [-1  3  2 -4]
 [ 3 -1  4  2]]


In [3]:
b = np.array([[5, 16, -2, 10]])
b = b.T

print(b)

[[ 5]
 [16]
 [-2]
 [10]]


In [9]:
Xnp = np.linalg.solve(A, b)
Xsp = sp.linalg.solve(A, b)

Xnp = Xnp.T
Xsp = Xsp.T

print("Xnp = ", Xnp)
print("Xsp = ", Xsp)

Xnp =  [[ 4.52 -0.6  -0.4  -1.28]]
Xsp =  [[ 4.52 -0.6  -0.4  -1.28]]


In [12]:
P, L, U = sp.linalg.lu(A)

#for debugging
print("L = ")
print(L)
print("U = ")
print(U)
print("P = ")
print(P)

L = 
[[ 1.          0.          0.          0.        ]
 [-0.25        1.          0.          0.        ]
 [ 0.5         0.8         1.          0.        ]
 [ 0.75        0.2         0.06557377  1.        ]]
U = 
[[ 4.         -2.          5.          1.        ]
 [ 0.          2.5         3.25       -3.75      ]
 [ 0.          0.         -6.1         5.5       ]
 [ 0.          0.          0.          1.63934426]]
P = 
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [10]:
LU, P = sp.linalg.lu_factor(A)
XscpLU = sp.linalg.lu_solve((LU, P), b)

#for debugging
print("LU = ")
print(LU)
print("P = ")
print(P)
print("XscpLU = ")
print(XscpLU)

LU = 
[[ 4.         -2.          5.          1.        ]
 [-0.25        2.5         3.25       -3.75      ]
 [ 0.5         0.8        -6.1         5.5       ]
 [ 0.75        0.2         0.06557377  1.63934426]]
P = 
[1 2 2 3]
XscpLU = 
[[ 4.52]
 [-0.6 ]
 [-0.4 ]
 [-1.28]]
